# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api_proxy_service import api_pb2 as api__proxy__service_dot_api__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in api_proxy_service/api_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class APIProxyServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.VideoTemplateList = channel.unary_unary(
                '/wati.ai_platform.protocol.api_proxy_service.APIProxyService/VideoTemplateList',
                request_serializer=api__proxy__service_dot_api__pb2.VideoTemplateListRequest.SerializeToString,
                response_deserializer=api__proxy__service_dot_api__pb2.VideoTemplateListResponse.FromString,
                _registered_method=True)
        self.VideoTemplateGet = channel.unary_unary(
                '/wati.ai_platform.protocol.api_proxy_service.APIProxyService/VideoTemplateGet',
                request_serializer=api__proxy__service_dot_api__pb2.VideoTemplateGetRequest.SerializeToString,
                response_deserializer=api__proxy__service_dot_api__pb2.VideoTemplateGetResponse.FromString,
                _registered_method=True)
        self.SpeakerList = channel.unary_unary(
                '/wati.ai_platform.protocol.api_proxy_service.APIProxyService/SpeakerList',
                request_serializer=api__proxy__service_dot_api__pb2.SpeakerListRequest.SerializeToString,
                response_deserializer=api__proxy__service_dot_api__pb2.SpeakerListResponse.FromString,
                _registered_method=True)
        self.SpeakerGet = channel.unary_unary(
                '/wati.ai_platform.protocol.api_proxy_service.APIProxyService/SpeakerGet',
                request_serializer=api__proxy__service_dot_api__pb2.SpeakerGetRequest.SerializeToString,
                response_deserializer=api__proxy__service_dot_api__pb2.SpeakerGetResponse.FromString,
                _registered_method=True)
        self.VideoList = channel.unary_unary(
                '/wati.ai_platform.protocol.api_proxy_service.APIProxyService/VideoList',
                request_serializer=api__proxy__service_dot_api__pb2.VideoListRequest.SerializeToString,
                response_deserializer=api__proxy__service_dot_api__pb2.VideoListResponse.FromString,
                _registered_method=True)
        self.VideoGet = channel.unary_unary(
                '/wati.ai_platform.protocol.api_proxy_service.APIProxyService/VideoGet',
                request_serializer=api__proxy__service_dot_api__pb2.VideoGetRequest.SerializeToString,
                response_deserializer=api__proxy__service_dot_api__pb2.VideoGetResponse.FromString,
                _registered_method=True)
        self.VideoTaskNew = channel.unary_unary(
                '/wati.ai_platform.protocol.api_proxy_service.APIProxyService/VideoTaskNew',
                request_serializer=api__proxy__service_dot_api__pb2.VideoNewTaskRequest.SerializeToString,
                response_deserializer=api__proxy__service_dot_api__pb2.VideoNewTaskResponse.FromString,
                _registered_method=True)
        self.VideoTaskStatusGet = channel.unary_unary(
                '/wati.ai_platform.protocol.api_proxy_service.APIProxyService/VideoTaskStatusGet',
                request_serializer=api__proxy__service_dot_api__pb2.VideoTaskStatusGetRequest.SerializeToString,
                response_deserializer=api__proxy__service_dot_api__pb2.VideoTaskStatusGetResponse.FromString,
                _registered_method=True)
        self.VideoUpdate = channel.unary_unary(
                '/wati.ai_platform.protocol.api_proxy_service.APIProxyService/VideoUpdate',
                request_serializer=api__proxy__service_dot_api__pb2.VideoUpdateRequest.SerializeToString,
                response_deserializer=api__proxy__service_dot_api__pb2.VideoUpdateResponse.FromString,
                _registered_method=True)
        self.VideoDelete = channel.unary_unary(
                '/wati.ai_platform.protocol.api_proxy_service.APIProxyService/VideoDelete',
                request_serializer=api__proxy__service_dot_api__pb2.VideoDeleteRequest.SerializeToString,
                response_deserializer=api__proxy__service_dot_api__pb2.VideoDeleteResponse.FromString,
                _registered_method=True)
        self.SendWATIMessage = channel.unary_unary(
                '/wati.ai_platform.protocol.api_proxy_service.APIProxyService/SendWATIMessage',
                request_serializer=api__proxy__service_dot_api__pb2.SendWATIMessageRequest.SerializeToString,
                response_deserializer=api__proxy__service_dot_api__pb2.SendWATIMessageResponse.FromString,
                _registered_method=True)


class APIProxyServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def VideoTemplateList(self, request, context):
        """List video templates.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VideoTemplateGet(self, request, context):
        """Get the specified template by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SpeakerList(self, request, context):
        """// 罗列所有的脚本模版.
        // List all script templates.
        rpc VideoTemplateScriptList(VideoTemplateScriptListRequest) returns (VideoTemplateScriptListResponse) {
        option (google.api.http) = {
        get: "/v1/video/templates/{template_id}/scripts"
        };
        }

        // 获取指定脚本模版.
        // Get the specified script template by ID.
        rpc VideoTemplateScriptGet(VideoTemplateScriptGetRequest) returns (VideoTemplateScriptGetResponse) {
        option (google.api.http) = {
        get: "/v1/video/templates/{template_id}/scripts/{script_id}"
        };
        }

        List all speakers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SpeakerGet(self, request, context):
        """Get the specified speaker by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VideoList(self, request, context):
        """List all videos generated by the specified user.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VideoGet(self, request, context):
        """Get the specified video by video ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VideoTaskNew(self, request, context):
        """Create a video generation task.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VideoTaskStatusGet(self, request, context):
        """Check a video generation task status by video ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VideoUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VideoDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendWATIMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_APIProxyServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'VideoTemplateList': grpc.unary_unary_rpc_method_handler(
                    servicer.VideoTemplateList,
                    request_deserializer=api__proxy__service_dot_api__pb2.VideoTemplateListRequest.FromString,
                    response_serializer=api__proxy__service_dot_api__pb2.VideoTemplateListResponse.SerializeToString,
            ),
            'VideoTemplateGet': grpc.unary_unary_rpc_method_handler(
                    servicer.VideoTemplateGet,
                    request_deserializer=api__proxy__service_dot_api__pb2.VideoTemplateGetRequest.FromString,
                    response_serializer=api__proxy__service_dot_api__pb2.VideoTemplateGetResponse.SerializeToString,
            ),
            'SpeakerList': grpc.unary_unary_rpc_method_handler(
                    servicer.SpeakerList,
                    request_deserializer=api__proxy__service_dot_api__pb2.SpeakerListRequest.FromString,
                    response_serializer=api__proxy__service_dot_api__pb2.SpeakerListResponse.SerializeToString,
            ),
            'SpeakerGet': grpc.unary_unary_rpc_method_handler(
                    servicer.SpeakerGet,
                    request_deserializer=api__proxy__service_dot_api__pb2.SpeakerGetRequest.FromString,
                    response_serializer=api__proxy__service_dot_api__pb2.SpeakerGetResponse.SerializeToString,
            ),
            'VideoList': grpc.unary_unary_rpc_method_handler(
                    servicer.VideoList,
                    request_deserializer=api__proxy__service_dot_api__pb2.VideoListRequest.FromString,
                    response_serializer=api__proxy__service_dot_api__pb2.VideoListResponse.SerializeToString,
            ),
            'VideoGet': grpc.unary_unary_rpc_method_handler(
                    servicer.VideoGet,
                    request_deserializer=api__proxy__service_dot_api__pb2.VideoGetRequest.FromString,
                    response_serializer=api__proxy__service_dot_api__pb2.VideoGetResponse.SerializeToString,
            ),
            'VideoTaskNew': grpc.unary_unary_rpc_method_handler(
                    servicer.VideoTaskNew,
                    request_deserializer=api__proxy__service_dot_api__pb2.VideoNewTaskRequest.FromString,
                    response_serializer=api__proxy__service_dot_api__pb2.VideoNewTaskResponse.SerializeToString,
            ),
            'VideoTaskStatusGet': grpc.unary_unary_rpc_method_handler(
                    servicer.VideoTaskStatusGet,
                    request_deserializer=api__proxy__service_dot_api__pb2.VideoTaskStatusGetRequest.FromString,
                    response_serializer=api__proxy__service_dot_api__pb2.VideoTaskStatusGetResponse.SerializeToString,
            ),
            'VideoUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.VideoUpdate,
                    request_deserializer=api__proxy__service_dot_api__pb2.VideoUpdateRequest.FromString,
                    response_serializer=api__proxy__service_dot_api__pb2.VideoUpdateResponse.SerializeToString,
            ),
            'VideoDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.VideoDelete,
                    request_deserializer=api__proxy__service_dot_api__pb2.VideoDeleteRequest.FromString,
                    response_serializer=api__proxy__service_dot_api__pb2.VideoDeleteResponse.SerializeToString,
            ),
            'SendWATIMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendWATIMessage,
                    request_deserializer=api__proxy__service_dot_api__pb2.SendWATIMessageRequest.FromString,
                    response_serializer=api__proxy__service_dot_api__pb2.SendWATIMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wati.ai_platform.protocol.api_proxy_service.APIProxyService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('wati.ai_platform.protocol.api_proxy_service.APIProxyService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class APIProxyService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def VideoTemplateList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wati.ai_platform.protocol.api_proxy_service.APIProxyService/VideoTemplateList',
            api__proxy__service_dot_api__pb2.VideoTemplateListRequest.SerializeToString,
            api__proxy__service_dot_api__pb2.VideoTemplateListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VideoTemplateGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wati.ai_platform.protocol.api_proxy_service.APIProxyService/VideoTemplateGet',
            api__proxy__service_dot_api__pb2.VideoTemplateGetRequest.SerializeToString,
            api__proxy__service_dot_api__pb2.VideoTemplateGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SpeakerList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wati.ai_platform.protocol.api_proxy_service.APIProxyService/SpeakerList',
            api__proxy__service_dot_api__pb2.SpeakerListRequest.SerializeToString,
            api__proxy__service_dot_api__pb2.SpeakerListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SpeakerGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wati.ai_platform.protocol.api_proxy_service.APIProxyService/SpeakerGet',
            api__proxy__service_dot_api__pb2.SpeakerGetRequest.SerializeToString,
            api__proxy__service_dot_api__pb2.SpeakerGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VideoList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wati.ai_platform.protocol.api_proxy_service.APIProxyService/VideoList',
            api__proxy__service_dot_api__pb2.VideoListRequest.SerializeToString,
            api__proxy__service_dot_api__pb2.VideoListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VideoGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wati.ai_platform.protocol.api_proxy_service.APIProxyService/VideoGet',
            api__proxy__service_dot_api__pb2.VideoGetRequest.SerializeToString,
            api__proxy__service_dot_api__pb2.VideoGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VideoTaskNew(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wati.ai_platform.protocol.api_proxy_service.APIProxyService/VideoTaskNew',
            api__proxy__service_dot_api__pb2.VideoNewTaskRequest.SerializeToString,
            api__proxy__service_dot_api__pb2.VideoNewTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VideoTaskStatusGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wati.ai_platform.protocol.api_proxy_service.APIProxyService/VideoTaskStatusGet',
            api__proxy__service_dot_api__pb2.VideoTaskStatusGetRequest.SerializeToString,
            api__proxy__service_dot_api__pb2.VideoTaskStatusGetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VideoUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wati.ai_platform.protocol.api_proxy_service.APIProxyService/VideoUpdate',
            api__proxy__service_dot_api__pb2.VideoUpdateRequest.SerializeToString,
            api__proxy__service_dot_api__pb2.VideoUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VideoDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wati.ai_platform.protocol.api_proxy_service.APIProxyService/VideoDelete',
            api__proxy__service_dot_api__pb2.VideoDeleteRequest.SerializeToString,
            api__proxy__service_dot_api__pb2.VideoDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendWATIMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/wati.ai_platform.protocol.api_proxy_service.APIProxyService/SendWATIMessage',
            api__proxy__service_dot_api__pb2.SendWATIMessageRequest.SerializeToString,
            api__proxy__service_dot_api__pb2.SendWATIMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
